name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

env:
  resource_group: aml-rg
  aml_workspace_name: amlwp

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    needs: [linting]
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Use Python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: | 
          pytest $GITHUB_WORKSPACE/tests/test_train.py
  train-dev:
    name: train-dev
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Experimentation job
      run: az ml job create --file $GITHUB_WORKSPACE/src/job.yml --workspace-name $aml_workspace_name --resource-group $resource_group --stream
  train-prod:
    runs-on: ubuntu-latest
    needs: [train-dev]
    environment:
      prod
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Training Production job
      run: az ml job create --file $GITHUB_WORKSPACE/src/job-prod.yml --workspace-name $aml_workspace_name --resource-group $resource_group 


