name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

env:
  resource_group: aml-rg
  aml_workspace_name: amlwp

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Experimentation job
      run: az ml job create --file $GITHUB_WORKSPACE/src/job.yml --workspace-name $aml_workspace_name --resource-group $resource_group 


